name: Jack the IT Builder
description: Blogging about Architecture of Software
meta_description: "Juan Olivera, Blogging about Architecture of Software"

#markdown: redcarpet
markdown: kramdown
#highlighter: pygments
highlighter: rouge
logo: false
paginate: 15
baseurl: /
#domain_name: 'http://jp_olivo.github.com'
domain_name: 'jpolivo.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://jpolivo.github.io'
#url:            'http://localhost:4000'
author:         'Juan Olivera'
